### ISSUE TITLE
Numbers in elements are actually strings

### ISSUE THREAD

**Issue by dev-zero** [nickroberts404/Mendeleev#1]
The documentation on https://www.npmjs.com/package/mendeleev says:

```javascript
hydrogen == {  
    name:"hydrogen",
    symbol:"H",
    type:"other-nonmetal",
    number:1,
    mass:1.008,
    period:1,
    group:1,
    melting:14.01,
    boiling:20.28,
    density:0.00008988,
    electronegativity:2.20,
    radius:25,
    valence:1,
    specificheat:14.304
}
```

But looking at the `elements.json` shows that all the numbers are actually strings:

```json
   "H":{  
      "name":"hydrogen",
      "symbol":"H",
      "type":"other-nonmetal",
      "number":"1",
      "mass":"1.008",
      "period":"1",
      "group":"1",
      "melting":"14.01",
      "boiling":"20.28",
      "density":"0.00008988",
      "electronegativity":"2.20",
      "radius":"25",
      "valence":"1",
      "specificheat":"14.304",
      "comment":""
   }
```

... which makes comparisons like `elementA.number < elementB.number` unexpectedly lexicographic comparisons.

**Comment by nicorobo** [comment]
Thanks for noticing this! Apparently the values were always multiplied/divided by something before being used, implicitly casting them to numbers.  I just changed it with commit 1084b2c9f1f6c70da80a2c78e836529878e2cdad.
